name: "Emmanuel Menon's Blog"
author: 'Emmanuel Menon'
url: 'https://www.emmanuelmenon.com'
description: 'yikes'
lang: 'en_AU'
social:
  links:
    - https://github.com/emmanuelmenon
    - https://letterboxd.com/emmanuelmenon
markdown: kramdown
permalink: '/:year/:month/:day/:title/'
paginate: 5
plugins:
    - jekyll-paginate
    - jekyll-seo-tag
    - rouge
exclude:
    - README.md
    - Gemfile.lock
    - Gemfile
    - Rakefile
excerpt_separator: '<!--more-->'
highlighter: rouge
